package connecthub.frontend.homepage;

import connecthub.backend.database.GroupDatabase;
import connecthub.backend.models.group.Group;
import connecthub.backend.models.group.GroupMember;
import java.awt.Component;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JScrollPane;

public class GroupsPanel extends javax.swing.JPanel {
    private String userId;
    
    public GroupsPanel(String userId) {
        try {
            initComponents();
            this.userId = userId;
            this.setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
            this.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10)); // Add padding around the panel
            
            // get list of groups user is in
            GroupDatabase groupDatabse = GroupDatabase.getInstance();
            List<Group> groups = groupDatabse.loadGroups();
            List<Group> userGroups = new ArrayList<>();
            for(Group group : groups) {
                List<GroupMember> groupMembers = group.getMembers();
                for(GroupMember groupMember : groupMembers) {
                    if(groupMember.getUserId().equals(userId)) {
                        userGroups.add(group);
                        break;
                    }
                }
            }
            if(!userGroups.isEmpty()) {
                // Create DefaultListModel and add groups
                DefaultListModel<Group> listModel = new DefaultListModel<>();
                for (Group group : userGroups) {
                    listModel.addElement(group);
                }
                
                // Create the JList and set the model
                JList<Group> jGroupList = new JList<>(listModel);

                // Add the JList to the panel
                JScrollPane scrollPane = new JScrollPane(jGroupList);
                this.add(scrollPane);
            } else {
                JLabel noGroupsLabel = new JLabel("No groups found.");
                this.add(noGroupsLabel);
            }
        } catch (IOException ex) {
            Logger.getLogger(GroupsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void refresh() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
