package connecthub.frontend.homepage;

import connecthub.backend.models.Post;
import connecthub.backend.models.User;
import connecthub.backend.services.PostService;
import connecthub.backend.services.UserService;
import connecthub.backend.utils.factories.ServiceFactory;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.SwingUtilities;

public class NewsFeedPanel extends javax.swing.JPanel {
    private final UserService userService;
    private final PostService postService;
    private final User user;
    private PostsPanel postsPanel;

    public NewsFeedPanel(List<Post> posts, User user) {
        initComponents();
        userService = UserService.getInstance();
        postService = ServiceFactory.createPostService();
        this.user = user;
        this.setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        this.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10)); // Add padding around the panel
        this.setOpaque(false);
        displayPosts(posts);
    }
    

    private void displayPosts(List<Post> posts) {
        if (postsPanel == null) {
            postsPanel = new PostsPanel(posts, user.getUserId());
            jDisplayPosts.setViewportView(postsPanel);
        } else {
            postsPanel.updatePosts(posts);
        }
        postsPanel.revalidate();
        postsPanel.repaint();
        jDisplayPosts.revalidate();
        jDisplayPosts.repaint();
        SwingUtilities.invokeLater(() -> {
            jDisplayPosts.getVerticalScrollBar().setUnitIncrement(8);
            jDisplayPosts.getVerticalScrollBar().setValue(0);
        });
}

    public void refresh(List<Post> posts) {
        displayPosts(posts);
        jDisplayPosts.getVerticalScrollBar().setValue(0); // reset to top
        revalidate();
        repaint();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g.create();
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        g2d.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BICUBIC);
        g2d.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDisplayPosts = new javax.swing.JScrollPane();

        setMinimumSize(new java.awt.Dimension(819, 627));
        setPreferredSize(new java.awt.Dimension(819, 627));

        jDisplayPosts.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jDisplayPosts.setMaximumSize(new java.awt.Dimension(500, 32767));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jDisplayPosts, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDisplayPosts, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jDisplayPosts;
    // End of variables declaration//GEN-END:variables

}
